# Generated by Django 2.2.28 on 2023-09-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatetrack',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_tracks', to='downloads.DownloadableVersion'),
        ),
    ]
