# Generated by Django 2.2.28 on 2023-10-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_dlv_move_from_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseversion',
            name='is_tagged',
            field=models.BooleanField(default=True),
        ),
    ]
